version: '4'
services:
  postgres:
    image: postgres:14.13
    container_name: postgresDB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: express
    volumes:
      - ./data:/data/db
